version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: cache
    ports:
      - "6379:6379"
    expose:
      - 6379
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis://cache
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
